export const META_CONSTANTS = {
	APP_TITLE: "Untitled"
};

export const GAMEPLAY_CONSTANTS = {
	CORRECT_ANSWER_POINTS: 40,
	INCORRECT_ANSWER_POINTS_MULTIPLIER: 0.5,
	INITIAL_LIVES: 3,
	RESULTS_DIALOG_DELAY: 1000,
	RESULTS_DIALOG_LINK_DELAY: 1200
};
